#!/bin/sh
# Exit on the first error
set -e

# All echo output will go to the build log. View with 'dotcloud dlogs'
echo "START BUILDER SCRIPT"

VERSION=3.0.2
TARBALL=rabbitmq-server-generic-unix-$VERSION.tar.gz
URL=http://www.rabbitmq.com/releases/rabbitmq-server/v$VERSION/$TARBALL
DESTDIR=$HOME/rabbitmq_server-$VERSION 
SYMLINK=$HOME/rabbitmq_server

if [ ! -d $DESTDIR ]
then
  echo "Fetching $TARBALL to create $DESTDIR"
  wget $URL
  tar -C$HOME -zxf $TARBALL
  if [ -L $SYMLINK ]
  then
    echo "Looks like you have an old link to $SYMLINK. Removing and replacing."
    rm $SYMLINK
  fi
  ln -s $DESTDIR $SYMLINK
else
  echo "I believe I already have $DESTDIR ..."
  ls -l $HOME
  echo "---------------------------------------------"
fi

# The default process will be 'run' and should be in the HOME directory
cp $(dirname $0)/run $HOME/run

PWFILE=$HOME/password
if [ ! -f $PWFILE ]
then
  dd if=/dev/urandom bs=1 count=8 | base64 > $PWFILE
  echo "Password was generated in $PWFILE: $(cat $PWFILE)"
else
  echo "Remember, the password is in $PWFILE."
fi
