#!/bin/sh
export RABBITMQ_CONFIG_FILE=$HOME/rabbitmq
cat >$RABBITMQ_CONFIG_FILE.config <<EOF
[
  {rabbit, [
    {tcp_listeners, [$PORT_AMQP]},
    {vm_memory_high_watermark, 0.001},
    {default_user, <<"rabbitmq">>},
    {default_pass, <<"$(cat $HOME/password)">>}
  ]}
].
EOF
exec $HOME/rabbitmq_server/sbin/rabbitmq-server